### PR TITLE
Organize code + Background music system

### PR DESCRIPTION
**Pull request by Gareeb-coder**

### CODE REVIEW

**Comment by hartalex** [comment]
I’m not a fan of the coding style of declaring multiple variables in a single line.  Can you change it back?  Also I’m not sure I can accept the music with out attribution.  Who created the music and how is it licensed?

**Comment by UdhayBrahmi** [comment]
> I’m not a fan of the coding style of declaring multiple variables in a single line. Can you change it back? Also I’m not sure I can accept the music with out attribution. Who created the music and how is it licensed?

Ok bro, I will change if u want so. 😇
My views :- It's better to organize things in programming. 🙂
I am new to Github. But not to programming. 😎 So i change it according to what I experience while learning programming.i.e. DRY
LAST WORDS :- I will change it as u want. 🌹🙏🏻

**Comment by Gareeb-coder** [comment]
[https://mobcup.net/ringtone/temple-run-2-xjcyy62b](url)
The link of the side from where music file is being downloaded is given above.
I give all credits of music file to this Website owner..... HOPE YOU GOT UR ANSWER.

**Comment by Gareeb-coder** [comment]
And the answer to ur question about not a fan of organizing code is GIVEN BELOW.
"It will depend on you whether you want ur code to be in organize form or not. If yes then merge it otherwise leave it as it is and let other developer find its answer 😊".

I HOPE YOU GOT YOUR ANSWER IN DETAIL.

**Comment by hartalex** [comment]
I checked out the site the music was downloaded.  As this looks to be a site that anyone can upload music too,  I can't be certain who actually composed the music, and I feel like we'd be opening our selves to getting sued for using anything from this site.   I'd feel more comfortable with music that we can definitively attribute to a CC-SA license. (Creative Commons - Share Alike).

**Pull request closed without merging**
